---
title: "kqf_proj"
author: "Evan Krause"
date: "2022-11-11"
output: html_document
---

#Required packages
```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(lubridate)
library(data.table)
require(here)
require(ggplot2)
require(visdat)
```

#Functions
```{r, echo=FALSE}
import_pest_csv <- function(x) {
  if (getwd() == "C:/Users/user/OneDrive - University of Massachusetts/kqf_project") {
    fread(here("data", x))
    
  } else {
    setwd("C:/Users/user/OneDrive - University of Massachusetts/kqf_project")
    fread(here("data", x))
    
  }
}
import_fruit_csv <- function(x) {
  if (getwd() == "C:/Users/user/OneDrive - University of Massachusetts/kqf_project") {
    fread(
      here("data", x)
      )
    
    
  } else {
    setwd("C:/Users/user/OneDrive - University of Massachusetts/kqf_project")
    fread(
      here("data", x),
      select = c(
        "grower_id",
        "deliver_date",
        "Bog",
        "Variety",
        "Rot",
        "GTL",
        "NetWeight",
        "kqf_pre",
        "kqf_final"
      )
    )
    
  }
}
```

#Decas fruit data import and clean
```{r}
#init import
fruit_12 <- import_fruit_csv("grower_yield_rpt_2012.csv")
fruit_13 <- import_fruit_csv("grower_yield_rpt_2013.csv")
fruit_14 <- import_fruit_csv("grower_yield_rpt_2014.csv")
fruit_15 <- import_fruit_csv("grower_yield_rpt_2015.csv")
fruit_16 <- import_fruit_csv("grower_yield_rpt_2016.csv")
fruit_17 <- import_fruit_csv("grower_yield_rpt_2017.csv")
fruit_18 <- import_fruit_csv("grower_yield_rpt_2018.csv")

#date coercion
fruit_12$date <-
  as.Date(parse_date_time(fruit_12$Delivered, "mdy"))
fruit_13$date <-
  as.Date(parse_date_time(fruit_13$Delivered, "mdy"))
fruit_14$date <-
  as.Date(parse_date_time(fruit_14$Delivered, "mdy"))
fruit_15$date <-
  as.Date(parse_date_time(fruit_15$Delivered, "mdy"))
fruit_16$date <-
  as.Date(parse_date_time(fruit_16$Delivered, "mdy"))
fruit_17$date <-
  as.Date(parse_date_time(fruit_17$Delivered, "mdy"))
fruit_18$date <-
  as.Date(parse_date_time(fruit_18$Delivered, "mdy"))

#table bind by row
decas_fruit_data <-
  rbind(fruit_12,
        fruit_13,
        fruit_14,
        fruit_15,
        fruit_16,
        fruit_17,
        fruit_18,
        fill = T)

rm(fruit_12,
   fruit_13,
   fruit_14,
   fruit_15,
   fruit_16,
   fruit_17,
   fruit_18)

#date manipulations
decas_fruit_data <- decas_fruit_data %>%
  relocate(deliver_date)

decas_fruit_data$date <-
  (parse_date_time(decas_fruit_data$deliver_date, orders = "mdy"))

decas_fruit_data$deliver_date <- NULL
decas_fruit_data <- decas_fruit_data %>%
  relocate(date)

#filter dates w/o rot and select/rename relevant columns
decas_fruit_data <- decas_fruit_data %>%
  filter(is.na(Rot) == F) %>%
  select(date,
         grower_id,
         Bog,
         LotID,
         GTL,
         Rot,
         Color,
         Variety,
         `Pack Out %`,
         kqf_pre,
         kqf_final)
colnames(decas_fruit_data) <- c("date", "grower_id",
                                "bog",
                                "lot_id",
                                "gtl",
                                "rot",
                                "color",
                                "variety",
                                "pack_out_pct",
                                "kqf_pre",
                                "kqf_final")
```

#CIG fruit data import/clean
```{r}

cig_fruit_data <- fread(here("data", "cig_yield_bloom.csv"))

```

#Decas pest data import/clean
```{r warning=FALSE}
pest_decas <- import_pest_csv("pest_use_decas.csv")

pest_decas <- pest_decas %>%
  mutate(date = parse_date_time(application_date, orders = "mdy"))
pest_decas$application_date <- NULL

pest_decas <- pest_decas %>%
  relocate(date) %>%
  select(date, treatment, active_ingredient, grower, bog) %>%
  filter(active_ingredient != "NULL")
```

#CIG pest data import/clean
```{r}
pest_cig <- import_pest_csv("pest_use_cig.csv")
pest_cig <- pest_cig %>%
  mutate(date =  parse_date_time(application_date, orders = "ymd"))

pest_cig$application_date <- NULL
pest_cig <- pest_cig %>%
  relocate(date) %>%
  select(date, treatment, active_ingredient, grower, Bog)

colnames(pest_cig) <- c("date",
                        "treatment",
                        "active_ingredient",
                        "grower",
                        "bog")

```
#Pest data combine/clean
```{r warning=FALSE}
pest_data <- rbind(pest_cig,
                   pest_decas,
                   fill = T)
#rm(pest_cig, pest_decas)

#combine duplicated names
pest_data$active_ingredient <-
  str_replace_all(
    pest_data$active_ingredient,
    c(
      "Manganese ethylenebisdithiocarbamate" = "EBDC",
      "Mancozeb" = "EBDC",
      "EDBC" = "EBDC",
      "Polyoxin D Zinc Salt" = "Polyoxin D",
      "Polyoxin D zinc salt" = "Polyoxin D"
    )
  )

#filter by fungicide
fungicide_use <- pest_data %>%
  filter(
    active_ingredient %in% c(
      "Copper Hydroxide",
      "Cuprous Oxide",
      "Polyoxin D",
      "Chlorothalonil",
      "Azoxystrobin",
      "Fenbuconazole",
      "Fosetyl-Al",
      "EBDC",
      "Ferbam"
    )
  )
rm(pest_data)

other_ingredients <- c("Cuprous Oxide",
                       "Fosetyl-Al",
                       "Polyoxin D")

fungicide_use <- fungicide_use %>%
  mutate(ingredient = fct_collapse(active_ingredient,
                                    other = other_ingredients)) %>%
  select(-active_ingredient) 

vis_miss(fungicide_use)
```

#Climate parameter import
```{r}
#climate parameter import----
temp_precip <- fread(here("data", "kqf_temp_precip_values.csv"))

colnames(temp_precip) <- c("month",
                                   "year",
                                   "avg_temp",
                                   "precip_total")

temp_precip$avg_temp <- as.numeric(temp_precip$avg_temp)

rot_temp <- temp_precip %>%
  filter(year %in% c(2013:2018))

vis_miss(temp_precip)
```

#Combined fruit/pest/temp data 
```{r}
comb_data <-
  merge(decas_fruit_data,
        fungicide_use,
        by = c("date", "grower_id", "bog"),
        all = T,
        suffixes = c("_fruit", "_pest"),
        no.dups = F)

#year and month columns
comb_data$year <- format(as.Date(comb_data$date, format="%Y-%m-%d"),"%Y")
comb_data$month <- format(as.Date(comb_data$date, format= "%Y-%m-%d"), "%m")


comb_data <- comb_data %>%
  select(date, grower_id,
         gtl, bog,
         rot, color,
         variety, kqf_pre,
         kqf_final,treatment,
         ingredient, year,
         month) %>%
  arrange(desc(date)) 
#%>%
 # unite(grower_id, c("grower_id", "grower"))

  



#log_rot col
comb_data <- comb_data %>%
  mutate(log_rot = log(rot)) 

vis_miss(comb_data)

rot_data <- comb_data %>%
  filter(is.na(rot) == F)

rot_data %>%
  select(gtl, rot, color, kqf_final) %>%
  vis_cor()
```

#Cleaning
```{r}
#pest_dupes <- pest_data %>%
  #filter(duplicated(pest_data))

#fruit_dupes <- decas_fruit_data %>%
  #filter(duplicated(decas_fruit_data))

#comb_dupes <- comb_data %>%
  #filter(duplicated(comb_data))

#fruit_unique <- distinct(decas_fruit_data)

#pest_data_unique <- distinct(pest_data)

#Variety col clean

other_varieties = c("OE", "ORST", "OH", "OM",
                    "GR", "OB", "SN", "GD",
                    "", "MC", "SK", "ORHO",
                    "PM", "OS")
comb_data <- comb_data %>%
  mutate(variety_collapsed = fct_collapse(variety, 
                                          other = other_varieties))
comb_data %>%
  count(variety_collapsed, sort = T)

#treatment col clean
comb_missing <- comb_data %>%
  mutate(miss_treat = is.na(treatment)) %>%
  group_by(miss_treat) %>%
  arrange(miss_treat) %>%
  vis_miss()

```


#log Rot by kqf aov
```{r}
decas_rot_kqf <- decas_fruit_data %>%
  mutate(log_rot = log(rot) + 0.1)%>%
  filter(log_rot >= 0,
         is.na(kqf_final) == "FALSE")

other_varieties = c("OE", "ORST", "OH", "OM",
                    "GR", "OB", "SN",
                    "MC", "SK", "ORHO",
                    "OS")

decas_rot_kqf <- decas_rot_kqf %>%
  mutate(variety_coll = fct_collapse(variety, 
                                          other = other_varieties))

log_rot_kqf <- lm(decas_rot_kqf$log_rot ~ decas_rot_kqf$kqf_final)

aov(log_rot_kqf)
anova(log_rot_kqf)
logrot_resid <- hist(log_rot_kqf$residuals)
shapiro.test(log_rot_kqf$residuals)
log_rot_kqf


log_by_kqf <- boxplot(decas_rot_kqf$log_rot ~ decas_rot_kqf$kqf_final)


cor.test(decas_rot_kqf$kqf_final, decas_rot_kqf$log_rot, method = "spearman")

decas_rot_kqf %>%
  ggplot(aes(log_rot, color = variety_coll)) +
  geom_histogram(bins = 50) 

decas_rot_kqf %>%
  ggplot(aes(log_rot, color = variety_coll)) +
  geom_histogram(bins = 75) 


```

#plots----
```{r}
decas_rot_kqf %>%
  ggplot(aes(variety,log_rot)) + 
  geom_point()


temp_precip %>%
  filter(month == "July") %>%
  ggplot(aes(year, avg_temp, color = year)) +
  geom_point()

ggplot
```


